import { useState, useEffect } from "react";
import Head from "next/head";
import About from "../components/About";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [black, setBlack] = useState(false);

  useEffect(() => {
    const scrollListener = () => {
      if (window.scrollY > 10) {
        setBlack(true);
      } else {
        setBlack(false);
      }
    };

    window.addEventListener("scroll", scrollListener);

    return () => {
      window.removeEventListener("scroll", scrollListener);
    };
  }, []);

  return (
    <>
      {/* Header */}
      <Header black={black} />

      <div className={styles.container}>
        <Head>
          <title>Portfólio | Filipe Araujo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Hero */}
        <section id="hero">
          <Hero />
        </section>

        {/* About */}
        <section id="about">
          <About />
        </section>

        {/* Skills */}
        <section id="skills">
          <Skills />
        </section>

        {/* Projects */}
        <section id="projects">
          <Projects />
        </section>

        {/* Contact Me */}
        <section id="contact">
          <Contact />
        </section>
      </div>

    </>
  );
}
